/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection': RouteRecordInfo<
      '/inspection',
      '/inspection',
      Record<never, never>,
      Record<never, never>,
      | '/inspection/components/RuleConfigForm'
      | '/inspection/inspection-result'
      | '/inspection/rectification-order'
      | '/inspection/rule-config'
      | '/inspection/system-admin'
    >,
    '/inspection/components/RuleConfigForm': RouteRecordInfo<
      '/inspection/components/RuleConfigForm',
      '/inspection/components/RuleConfigForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/inspection-result': RouteRecordInfo<
      '/inspection/inspection-result',
      '/inspection/inspection-result',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/rectification-order': RouteRecordInfo<
      '/inspection/rectification-order',
      '/inspection/rectification-order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/rule-config': RouteRecordInfo<
      '/inspection/rule-config',
      '/inspection/rule-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/system-admin': RouteRecordInfo<
      '/inspection/system-admin',
      '/inspection/system-admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection-system': RouteRecordInfo<
      '/inspection-system',
      '/inspection-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/1/item-1': RouteRecordInfo<
      '/nav/1/item-1',
      '/nav/1/item-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/2': RouteRecordInfo<
      '/nav/2',
      '/nav/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/4': RouteRecordInfo<
      '/nav/4',
      '/nav/4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/5': RouteRecordInfo<
      '/nav/5',
      '/nav/5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/6': RouteRecordInfo<
      '/nav/6',
      '/nav/6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/7': RouteRecordInfo<
      '/nav/7',
      '/nav/7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/inspection.vue': {
      routes:
        | '/inspection'
        | '/inspection/components/RuleConfigForm'
        | '/inspection/inspection-result'
        | '/inspection/rectification-order'
        | '/inspection/rule-config'
        | '/inspection/system-admin'
      views:
        | 'default'
    }
    'src/pages/inspection/components/RuleConfigForm.vue': {
      routes:
        | '/inspection/components/RuleConfigForm'
      views:
        | never
    }
    'src/pages/inspection/inspection-result.vue': {
      routes:
        | '/inspection/inspection-result'
      views:
        | never
    }
    'src/pages/inspection/rectification-order.vue': {
      routes:
        | '/inspection/rectification-order'
      views:
        | never
    }
    'src/pages/inspection/rule-config.vue': {
      routes:
        | '/inspection/rule-config'
      views:
        | never
    }
    'src/pages/inspection/system-admin.vue': {
      routes:
        | '/inspection/system-admin'
      views:
        | never
    }
    'src/pages/inspection-system.vue': {
      routes:
        | '/inspection-system'
      views:
        | never
    }
    'src/pages/nav/1/item-1.vue': {
      routes:
        | '/nav/1/item-1'
      views:
        | never
    }
    'src/pages/nav/2.vue': {
      routes:
        | '/nav/2'
      views:
        | never
    }
    'src/pages/nav/4.vue': {
      routes:
        | '/nav/4'
      views:
        | never
    }
    'src/pages/nav/5.vue': {
      routes:
        | '/nav/5'
      views:
        | never
    }
    'src/pages/nav/6.vue': {
      routes:
        | '/nav/6'
      views:
        | never
    }
    'src/pages/nav/7.vue': {
      routes:
        | '/nav/7'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
