/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-config/': RouteRecordInfo<
      '/api-config/',
      '/api-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/change-protection/': RouteRecordInfo<
      '/change-protection/',
      '/change-protection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection': RouteRecordInfo<
      '/inspection',
      '/inspection',
      Record<never, never>,
      Record<never, never>,
      | '/inspection/'
      | '/inspection/admin/'
      | '/inspection/components/BlocklyIntegration'
      | '/inspection/components/BrickLibrary'
      | '/inspection/components/CsvUpload'
      | '/inspection/components/FeatToggle'
      | '/inspection/components/ModeSwitch'
      | '/inspection/order/'
      | '/inspection/result/'
      | '/inspection/result/inspection-result-drawer'
      | '/inspection/rule/'
      | '/inspection/rule/RuleConfigFormV2'
    >,
    '/inspection/': RouteRecordInfo<
      '/inspection/',
      '/inspection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/admin/': RouteRecordInfo<
      '/inspection/admin/',
      '/inspection/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/components/BlocklyIntegration': RouteRecordInfo<
      '/inspection/components/BlocklyIntegration',
      '/inspection/components/BlocklyIntegration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/components/BrickLibrary': RouteRecordInfo<
      '/inspection/components/BrickLibrary',
      '/inspection/components/BrickLibrary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/components/CsvUpload': RouteRecordInfo<
      '/inspection/components/CsvUpload',
      '/inspection/components/CsvUpload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/components/FeatToggle': RouteRecordInfo<
      '/inspection/components/FeatToggle',
      '/inspection/components/FeatToggle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/components/ModeSwitch': RouteRecordInfo<
      '/inspection/components/ModeSwitch',
      '/inspection/components/ModeSwitch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/order/': RouteRecordInfo<
      '/inspection/order/',
      '/inspection/order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/result/': RouteRecordInfo<
      '/inspection/result/',
      '/inspection/result',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/result/inspection-result-drawer': RouteRecordInfo<
      '/inspection/result/inspection-result-drawer',
      '/inspection/result/inspection-result-drawer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/rule/': RouteRecordInfo<
      '/inspection/rule/',
      '/inspection/rule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection/rule/RuleConfigFormV2': RouteRecordInfo<
      '/inspection/rule/RuleConfigFormV2',
      '/inspection/rule/RuleConfigFormV2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspection-system': RouteRecordInfo<
      '/inspection-system',
      '/inspection-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/1/item-1': RouteRecordInfo<
      '/nav/1/item-1',
      '/nav/1/item-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/2': RouteRecordInfo<
      '/nav/2',
      '/nav/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/4': RouteRecordInfo<
      '/nav/4',
      '/nav/4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/api-config/index.vue': {
      routes:
        | '/api-config/'
      views:
        | never
    }
    'src/pages/change-protection/index.vue': {
      routes:
        | '/change-protection/'
      views:
        | never
    }
    'src/pages/inspection.vue': {
      routes:
        | '/inspection'
        | '/inspection/'
        | '/inspection/admin/'
        | '/inspection/components/BlocklyIntegration'
        | '/inspection/components/BrickLibrary'
        | '/inspection/components/CsvUpload'
        | '/inspection/components/FeatToggle'
        | '/inspection/components/ModeSwitch'
        | '/inspection/order/'
        | '/inspection/result/'
        | '/inspection/result/inspection-result-drawer'
        | '/inspection/rule/'
        | '/inspection/rule/RuleConfigFormV2'
      views:
        | 'default'
    }
    'src/pages/inspection/index.vue': {
      routes:
        | '/inspection/'
      views:
        | never
    }
    'src/pages/inspection/admin/index.vue': {
      routes:
        | '/inspection/admin/'
      views:
        | never
    }
    'src/pages/inspection/components/BlocklyIntegration.vue': {
      routes:
        | '/inspection/components/BlocklyIntegration'
      views:
        | never
    }
    'src/pages/inspection/components/BrickLibrary.vue': {
      routes:
        | '/inspection/components/BrickLibrary'
      views:
        | never
    }
    'src/pages/inspection/components/CsvUpload.vue': {
      routes:
        | '/inspection/components/CsvUpload'
      views:
        | never
    }
    'src/pages/inspection/components/FeatToggle.vue': {
      routes:
        | '/inspection/components/FeatToggle'
      views:
        | never
    }
    'src/pages/inspection/components/ModeSwitch.vue': {
      routes:
        | '/inspection/components/ModeSwitch'
      views:
        | never
    }
    'src/pages/inspection/order/index.vue': {
      routes:
        | '/inspection/order/'
      views:
        | never
    }
    'src/pages/inspection/result/index.vue': {
      routes:
        | '/inspection/result/'
      views:
        | never
    }
    'src/pages/inspection/result/inspection-result-drawer.vue': {
      routes:
        | '/inspection/result/inspection-result-drawer'
      views:
        | never
    }
    'src/pages/inspection/rule/index.vue': {
      routes:
        | '/inspection/rule/'
      views:
        | never
    }
    'src/pages/inspection/rule/RuleConfigFormV2.vue': {
      routes:
        | '/inspection/rule/RuleConfigFormV2'
      views:
        | never
    }
    'src/pages/inspection-system.vue': {
      routes:
        | '/inspection-system'
      views:
        | never
    }
    'src/pages/nav/1/item-1.vue': {
      routes:
        | '/nav/1/item-1'
      views:
        | never
    }
    'src/pages/nav/2.vue': {
      routes:
        | '/nav/2'
      views:
        | never
    }
    'src/pages/nav/4.vue': {
      routes:
        | '/nav/4'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
